Add onelogin and okta SAML docs
firezone/firezone pull request #1108
Opened 2022-11-14 17:46 UTC by gongjason

2022-11-14 22:08 UTC, jamilbk requested changes
Some minor fixes but overall lgtm

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/README.mdx
> +## Provider Support
I feel like this may belong back at the top. If they're using Google or another unsupported provider, they'd probably want to find out sooner rather than later after generating certs. Maybe it belongs under `Prerequisites`

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/okta.mdx
> +description: Firezone's WireGuard based remote access platform supports using Okta as a single sign-on provider using a SAML 2.0 connector.
```suggestion
description: Firezone's WireGuard®-based remote access platform supports using Okta as a single sign-on provider using a SAML 2.0 connector.
```

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/okta.mdx
> +| Config ID | `Okta`     | Firezone uses this value to construct endpoints required in the SAML authentication flow (e.g., receiving assertions, login requests) |
```suggestion
| Config ID | `Okta`     | Firezone uses this value to construct endpoints required in the SAML authentication flow (e.g., receiving assertions, login requests).|
```

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/onelogin.mdx
> +| Config ID | `onelogin` | Firezone uses this value to construct endpoints required in the SAML authentication flow (e.g., receiving assertions, login requests) |
```suggestion
| Config ID | `onelogin` | Firezone uses this value to construct endpoints required in the SAML authentication flow (e.g., receiving assertions, login requests).|
```

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/onelogin.mdx
> +|---                      |---                                                                     |
```suggestion
|---                     |---                                                                     |
```

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/okta.mdx
> +Follow the steps below to activate the integration.
If we want to maintain the same tone as the OIDC guides:

```suggestion
Firezone supports Single Sign-On (SSO) using Okta through the generic SAML 2.0 connector. This guide will walk you through how to configure the integration.
```

2022-11-14 22:08 UTC, jamilbk commented on docs/docs/authenticate/saml/onelogin.mdx
> +Follow the steps below to activate the integration.
```suggestion
Firezone supports Single Sign-On (SSO) using OneLogin through the generic SAML 2.0 connector. This guide will walk you through how to configure the integration.
```

2022-11-15 06:40 UTC, jamilbk commented
Refs #1049

2022-11-15 19:04 UTC, gongjason commented on docs/docs/authenticate/saml/README.mdx
> +## Provider Support
I think the experience of clicking a provider, then coming back to complete the Pre-Reqs may not be great (people may miss that). I'll add some more context to the note to make sure they don't miss it.

2022-11-15 20:54 UTC, jamilbk approved these changes

2022-11-15 20:55 UTC, merged