Docs - Add whitelist sso doc
firezone/firezone pull request #1185
Opened 2022-12-08 00:11 UTC by gongjason

Continued the work on https://github.com/firezone/firezone/pull/995. Moved to a new PR due to too many merge conflicts.

2022-12-10 16:56 UTC, jamilbk requested changes

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/README.mdx
> +in separate VPC regions.
```suggestion
In this example the protected resource and Firezone are in separate VPC regions.
```

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/README.mdx
> +access list grows.
```suggestion
This is commonly done in place of maintaining an IP whitelist for
multiple team members, which becomes impossible to manage as the
access list grows and team members' IP addresses change.
```

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/README.mdx
> +By default, all traffic from users will be routed through the VPN server
```suggestion
By default, all traffic from team members will be routed through Firezone
```

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/_whitelist-sso.mdx
> +to a pre-defined network zone (IP range). You can set this to the IP of
typo

```suggestion
Some identity providers support restricting SSO access to a predefined CIDR range or list of IP addresses. You can set this to the IP address of
```

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/_whitelist-sso.mdx
> +connected to the VPN.
```suggestion
your Firezone gateway to restrict SSO to users connected to Firezone.
```

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/_whitelist-sso.mdx
> +title: Restrict SSO to VPN Users
```suggestion
title: Restrict SSO to Firezone Users
```

2022-12-10 16:56 UTC, jamilbk commented on docs/docs/user-guides/use-cases/nat-gateway/_whitelist-sso.mdx
> +enabled, you may be locked out Okta entirely when your VPN session
```suggestion
enabled, you may be locked out of Okta entirely when your VPN session
```

2022-12-10 21:28 UTC, gongjason commented
Oops, was renaming the branch to comply with conventional commits, but just realized that closes the PR. Will just have proper naming of branches going fwd to not lose the discussion here for this PR and https://github.com/firezone/firezone/pull/1187.

2022-12-16 00:45 UTC, jamilbk approved these changes

2022-12-17 16:32 UTC, merged