Add gateway and allow rule schemas
firezone/firezone pull request #1191
Opened 2022-12-08 23:23 UTC by akrousset

2022-12-10 22:07 UTC, jamilbk requested changes
A few comments

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/priv/repo/migrations/20221207180310_create_gateways.exs
> +      add(:name, :string, null: false, default: "default")
Maybe it's better to omit the default here to always require a name.

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/priv/repo/migrations/20221207180310_create_gateways.exs
> +      add(:registration_token_created_at, :utc_datetime_usec, null: false)
```suggestion
      add(:registration_token_created_at, :utc_datetime_usec, null: false)
      
      create unique_index(:devices, [:name])
```

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/allow_rules_test.exs
> +      allow_rule = allow_rule(%{gateway_id: gateway.id})
I think you need to create another `allow_rule()` belonging to another gateway for this test to be robust.

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/allow_rules_test.exs
> +      allow_rule = allow_rule(%{user_id: user.uuid})
I think you need to create another allow rule belonging to another user to ensure this is robust.

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/allow_rules_test.exs
> +      assert {:error, %Ecto.Changeset{}} = AllowRules.create_allow_rule(invalid_destination)
Probably want to use `==` to explicitly check for the error message you're expecting.

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/allow_rules_test.exs
> +      assert {:error, %Ecto.Changeset{}} = AllowRules.create_allow_rule(invalid_gateway)
Explicit error check with `==`

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/allow_rules_test.exs
> +      assert {:error, %Ecto.Changeset{} = change} =
Explicit error check

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/allow_rules_test.exs
> +      assert {:error, %Ecto.Changeset{} = change} =
Explicit error check `==`

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/fz_http/gateways_test.exs
> +      assert {:error, %Ecto.Changeset{}} = Gateways.create_gateway(duplicate_name)
Explicit error check with `==`

2022-12-10 22:07 UTC, jamilbk commented on apps/fz_http/test/support/fixtures/gateways_fixtures.ex
> +    name = attrs[:name] || "default"
Redundant with the field default -- think you should remove the field default and force this to be passed in?

2022-12-11 23:25 UTC, conectado approved these changes
LGTM.

Non-blocking nit picky suggestion left.

2022-12-11 23:25 UTC, conectado commented on apps/fz_http/lib/fz_http/allow_rules/allow_rule.ex
> +      message: "Port range start and end should be set or unset"
```suggestion
      message: "A port range needs both start and end. Additionally, a protocol requires a port range to be applied to."
```

2022-12-11 23:52 UTC, merged