Removes `hammer` and `hammer_plug` deps and their code references
firezone/firezone pull request #1230
Opened 2022-12-23 17:33 UTC by ssaunderss

Resolves Issue https://github.com/firezone/firezone/issues/1216

2022-12-23 17:54 UTC, AndrewDryga commented
@ssaunderss thank you! Can you please remove mentions of rate limits from the docs? 

This is the best kind of PRs where we just remove stuff :).

2022-12-23 19:28 UTC, jamilbk requested changes

2022-12-23 19:28 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/router.ex
> -    plug Hammer.Plug, @root_rate_limit
I think you need to also remove this attribute:

https://github.com/firezone/firezone/actions/runs/3767295825/jobs/6405527115#step:16:289

2022-12-23 23:52 UTC, ssaunderss commented
> @ssaunderss thank you! Can you please remove mentions of rate limits from the docs?

@AndrewDryga I only found one place in the docs that mentioned the in house rate limiter, everything else looks like its nginx related to me. Let me know if I missed anything!

2022-12-24 11:31 UTC, jamilbk approved these changes
Just in time for the upcoming REST API. Thanks @ssaunderss!

2022-12-24 11:32 UTC, merged