Rework configurations
firezone/firezone pull request #1352
Opened 2023-01-20 20:57 UTC by AndrewDryga

- [ ] All configs should support ENV variable overrides over DB values
- [ ] Adding a new field to DB value should automatically write ENV config to DB on app boot (so that we don't need migrations)
- [ ] Validate configs and report human-readable errors when something is wrong, telling where it's invalid (eg. env key X) and what's wrong with it
- [ ] Auto-generate docs

2023-01-20 23:14 UTC, jamilbk commented
This looks good! Just to clarify my understanding, some ENV vars won't have a corresponding Configuration entry and won't be validated (PHOENIX_PORT for example), but all runtime Configurations will be ENV-overridable, is that correct?

I know we briefly discussed a naming convention to link configuration-related env vars to actual Configurations (`FZ_*`?).

Also linking relevant configuration issues here to help me reference for the review.

- #1162 
- #1313
- #1343 
- #1266 
- firezone/product#413

2023-01-21 21:21 UTC, AndrewDryga commented
```
Some ENV vars won't have a corresponding Configuration entry and won't be validated (PHOENIX_PORT for example), but all runtime Configurations will be ENV-overridable, is that correct?
```
Yes. But FYI I did not plan to check for compile-time variables initially and the Ecto ones, maybe I will do it in the end if it's easy to integrate.

```
Thoughts on naming convention for configuration-related env vars? e.g. FZ_*
```
I feel like namespacing there is an overkill if we deal with containers, nobody is deploying firezone outside of them and inside a container, there are no name conflicts, it's just our app running.

```
Do we "let it crash" if ENV var is invalid on bootup?
```
We will raise for every variable that is invalid when the app boots.

2023-02-18 17:53 UTC, jamilbk requested changes
Really nice work, this looks great. Some minor suggestions and fixes noted.

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http/config/configuration.ex
> +    # wishing to configure Firezone with automated Infrastructure tools like
👍

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http/config/configuration/changeset.ex
> +            "can not be changed in UI, " <>
(nitpick): 
```suggestion
            "cannot be changed; " <>
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http/config/errors.ex
> +  @env_doc_url "https://docs.firezone.dev/reference/env-vars/#environment-variable-listing"
```suggestion
  @env_doc_url "https://www.firezone.dev/docs/reference/env-vars/#environment-variable-listing"
```

2023-02-18 17:53 UTC, jamilbk commented on www/docs/reference/env-vars.mdx
> +| **DEFAULT_CLIENT_DNS**                  | Comma-separated list of DNS servers to use for devices.<br /> <br />Leave this blank to omit the <code>DNS</code> section from generated configs.
I think this field is optional
```suggestion
| DEFAULT_CLIENT_DNS                  | Comma-separated list of DNS servers to use for devices.<br /> <br />Leave this blank to omit the <code>DNS</code> section from generated configs.                                                                                                                                                                                     | a list of IP separated by `,`                  |                               |
```

2023-02-18 17:53 UTC, jamilbk commented on www/docs/reference/env-vars.mdx
> +| CONNECTIVITY_CHECKS_INTERVAL | Periodicity in seconds to check for egress connectivity.                                                                       | integer | 3600    |
Ah I think I had updated this to be `43200` by default -- twice a day (trying to reduce amount of ingested data).
```suggestion
| CONNECTIVITY_CHECKS_INTERVAL | Periodicity in seconds to check for egress connectivity.                                                                       | integer | 43200    |
```

2023-02-18 17:53 UTC, jamilbk commented on www/docs/reference/env-vars.mdx
> +
Is this section duplicated from above?

2023-02-18 17:53 UTC, jamilbk commented on docs/docs/reference/env-vars.mdx
> +---
Ah I think this file is an artifact from the rebase -- see comment about duplicated sections.

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/test/fz_http/config_test.exs
> +  # describe "update_configuration/2 with name-based default_client_dns" do
Section can be removed?

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +        You can not add new change providers because this value is overriden using <%= config_override_source(
```suggestion
        You cannot add new change providers because this value is overridden using <%= config_override_source(
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +        You can not add new change providers because this value is overriden using <%= config_override_source(
```suggestion
        You cannot add new change providers because this value is overridden using <%= config_override_source(
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/customization.html.heex
> +        environment variable, you can not change it in the UI.
```suggestion
        environment variable; you cannot change it in the UI.
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +            This field was overriden using <%= config_override_source(vpn_session_duration) %>, you can not change it in UI.
```suggestion
            This field was overridden using <%= config_override_source(vpn_session_duration) %>; you cannot change it in UI.
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +              This value is overriden using <%= config_override_source(local_auth_enabled) %>, you can not change it in UI.
```suggestion
              This value is overridden using <%= config_override_source(local_auth_enabled) %>; you cannot change it in UI.
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +              This value is overriden using <%= config_override_source(
```suggestion
              This value is overridden using <%= config_override_source(
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +              ) %>, you can not change it in UI.
```suggestion
              ) %>; you cannot change it in UI.
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +              This value is overriden using <%= config_override_source(
```suggestion
              This value is overridden using <%= config_override_source(
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +              ) %>, you can not change it in UI.
```suggestion
              ) %>; you cannot change it in UI.
```

2023-02-18 17:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +            This value is overriden using <%= config_override_source(disable_vpn_on_oidc_error) %>, you can not change it in UI.
```suggestion
            This value is overridden using <%= config_override_source(disable_vpn_on_oidc_error) %>; you cannot change it in UI.
```

2023-02-21 14:12 UTC, jamilbk approved these changes, later dismissed

2023-02-21 16:38 UTC, merged