Website/updatefooter
firezone/firezone pull request #1569
Opened 2023-04-20 20:53 UTC by lilibobear

2023-04-21 01:11 UTC, jamilbk commented on www/docusaurus.config.js
> +          href: 'https://www.firezone.dev',
Consistent quote style:

```suggestion
          href: "https://www.firezone.dev",
```

2023-04-21 01:11 UTC, jamilbk commented on www/docusaurus.config.js
> +          height:50,
Consistent spacing:

```suggestion
          height: 50,
```

2023-04-21 01:12 UTC, jamilbk commented on www/docusaurus.config.js
> +        copyright: `Copyright © ${new Date().getFullYear()} Firezone, Inc. Wireguard® is a registered trademark of Jason A. Donenfeld.`,
Properly spell WireGuard

```suggestion
        copyright: `Copyright © ${new Date().getFullYear()} Firezone, Inc. WireGuard® is a registered trademark of Jason A. Donenfeld.`,
```

2023-04-21 01:35 UTC, jamilbk requested changes
Made some minor suggestions

2023-04-21 18:42 UTC, lilibobear reviewed
Incorporated comments.

2023-04-22 04:32 UTC, jamilbk approved these changes

2023-04-22 04:32 UTC, merged