Added footer links and form for beta signup.
firezone/firezone pull request #1579
Opened 2023-05-01 17:39 UTC by lilibobear

Added footer links and Hubspot signup.

2023-05-01 21:57 UTC, jamilbk requested changes
Added some suggestions

2023-05-01 21:57 UTC, jamilbk commented on www/src/pages/privacy.mdx
Probably want to rename this file to `_privacy.mdx` to mark it as draft

2023-05-01 21:57 UTC, jamilbk commented on www/src/pages/terms.mdx
Probably want to add a leading underscore `_terms.mdx` so this page isn't published until it's ready

2023-05-01 21:57 UTC, jamilbk commented on www/src/pages/self-hosted-firezone.mdx
> +description: Deploy Firezone self-hosted.
```suggestion
description: Deploy a self-hosted instance of Firezone.
```

2023-05-01 21:57 UTC, jamilbk commented on www/src/pages/index.mdx
> +    </div>
Indentation

```suggestion
<div className="row margin-top--xl">
  <div className="col col--6">
    <center>
   <a className="button button--primary" href="/docs/deploy">
    Deploy now
   </a>
   </center>
  </div>
  <div className="col col--6">
    <center>
   <a className="button button--primary" href="/beta/signup">
    Join the beta waitlist
   </a>
   </center>
  </div>
</div>
```

2023-05-01 21:57 UTC, jamilbk commented on www/src/pages/index.mdx
Indentation in this file needs to be fixed. See https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2023-05-01 21:57 UTC, jamilbk commented on www/src/pages/beta/signup.mdx
> +
Remove empty line
```suggestion
```

2023-05-01 21:57 UTC, jamilbk commented on www/docusaurus.config.js
> +      },
Comment out until the form is ready
```suggestion
      /*announcementBar: {
        id: 'support_us',
        content:
          'Firezone 1.0 is coming! <a target="_blank" rel="noopener noreferrer" href="/beta/signup">Sign up for early access.</a>',
        backgroundColor: '#fafbfc',
        textColor: '#091E42',
        isCloseable: false,
      },*/
```

2023-05-01 21:57 UTC, jamilbk commented on www/docusaurus.config.js
> +                // },
```suggestion
                // {
                  // label: "1.0",
                  // href: "/1.0/signup",
                // },
```

2023-05-01 21:57 UTC, jamilbk commented on www/docusaurus.config.js
> +          //},
```suggestion
          // {
           // href: "/1.0/signup",
           // label: "1.0",
          // position: "left",
          //},
```

2023-05-01 23:31 UTC, merged

2023-05-02 17:34 UTC, lilibobear commented on www/src/pages/privacy.mdx
agreed, I will do that in the future for draft pages!

2023-05-02 17:35 UTC, lilibobear commented on www/src/pages/terms.mdx
Agreed