connlib: Connection mock
firezone/firezone pull request #1721
Opened 2023-06-30 00:16 UTC by francesca64

Resolves #601

Setting the env var `CONNLIB_MOCK` when building through either `build-rust.sh` or `gradle` will activate the `mock` feature.

2023-06-30 13:37 UTC, jamilbk requested changes
@francesca64 Thanks for adding this! Could you please update the README.md in Connlib with a note on enabling this mock for the other devs?

Also cc @roop and @pratikvelani

2023-07-03 17:37 UTC, jamilbk approved these changes

2023-07-03 18:31 UTC, roop commented
@francesca64 I can see the mock calls if I add a `export CONNLIB_MOCK=1` to ./build-xcframework-dev.sh, so 👍🏻.

2023-07-03 18:45 UTC, conectado approved these changes

2023-07-03 18:49 UTC, merged