Add android client to the repo
firezone/firezone pull request #1738
Opened 2023-07-05 10:06 UTC by pratikvelani

- Add android client to the repo

2023-07-05 20:37 UTC, francesca64 approved these changes

2023-07-06 13:20 UTC, jamilbk commented
@pratikvelani ~~Could you [set up commit signing for Git](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)? I'll override for now but our branch protection rules require them.~~

<img width="876" alt="Screenshot 2023-07-06 at 6 19 37 AM" src="https://github.com/firezone/firezone/assets/167144/a0662e8e-8298-4503-9e05-9f8a03637489">

EDIT: Nevermind, I see you've set it up!

2023-07-06 13:37 UTC, jamilbk requested changes
Just missing a CI file similar to the one @roop added [here](https://github.com/firezone/firezone/pull/1737/files#r1254386100) but let's table that for another PR.

Also, I believe we're ditching the binary / package dependency for `Connlib` over a path-based one that builds alongside the main project. We can save that for another PR too.

2023-07-06 13:37 UTC, jamilbk commented on kotlin/android/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
```suggestion
   Copyright 2023 Firezone, Inc.
```

2023-07-06 13:37 UTC, jamilbk commented on kotlin/android/app/src/main/res/font/font.xml
> +    <font
Ah, we decided to go with `Source Sans Pro` for 1.0. I think a FIXME here is ok.

```suggestion
    <!-- FIXME: Use Source Sans Pro for 1.0 -->
    <font
```

2023-07-06 13:37 UTC, jamilbk commented on kotlin/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
Wow, thanks for adding all these assets! We'll probably want to double-check the background color as we near launch.

2023-07-06 13:37 UTC, jamilbk commented on kotlin/android/settings.gradle
> +            url = uri('https://maven.pkg.github.com/firezone/connlib')
Isn't this a path dependency now?

2023-07-06 13:40 UTC, jamilbk commented
@pratikvelani Looks like there are some linter issues, [one with mixed line endings](https://github.com/firezone/firezone/actions/runs/5475978599/jobs/9972839408?pr=1738#step:6:22) and other about whitespace. I think the whitespace one we can ignore for that directory if Android Studio is consistently violating the linter here.

2023-07-06 18:26 UTC, jamilbk commented on kotlin/android/settings.gradle
> +            url = uri('https://maven.pkg.github.com/firezone/connlib')
Edit: we can save this for another PR: https://github.com/firezone/product/issues/626

2023-07-06 18:30 UTC, jamilbk approved these changes

2023-07-06 18:56 UTC, pratikvelani commented
> @pratikvelani ~Could you [set up commit signing for Git](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)? I'll override for now but our branch protection rules require them.~
> 
> <img alt="Screenshot 2023-07-06 at 6 19 37 AM" width="876" src="https://user-images.githubusercontent.com/167144/251462836-a0662e8e-8298-4503-9e05-9f8a03637489.png">
> EDIT: Nevermind, I see you've set it up!

Yupe, I did the first commit from my MacBook it didnt have the gpg keys setup.

2023-07-07 11:54 UTC, merged