Feat/expire peers
firezone/firezone pull request #1739
Opened 2023-07-06 00:44 UTC by conectado

2023-07-06 20:30 UTC, francesca64 requested changes

2023-07-06 20:30 UTC, francesca64 commented on rust/connlib/libs/tunnel/src/peer.rs
> +        }
```suggestion
        !self.expires_at.is_some_and(|expires_at| expires_at <= Utc::now())
```

2023-07-06 20:30 UTC, francesca64 commented on rust/Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
I'm curious what the rationale is for disabling `default-features` and then manually specifying the default features anyway? I've noticed `default-features = false` is common throughout our dependency specifications, so I assume it's a policy we have?

2023-07-06 20:47 UTC, conectado commented on rust/Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
It's an undocumented convention I have, I found it makes it easier to track features long-term specially if we eventually wanted to move to some no-std environment and generally I prefer to be explicit about the features we use.

If you think it's better we can just use default features.

2023-07-06 22:08 UTC, francesca64 commented on rust/Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
I definitely understand wanting to make features less opaque, but this adds substantial tedium/noise and is rather unconventional. In the long-term that will be a stumbling block for open source contributors.

I'm guessing `cargo add` can't be configured to do this automatically? Do we have any concrete plans to support no-std?

2023-07-07 20:33 UTC, conectado commented on rust/Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
> I'm guessing cargo add can't be configured to do this automatically? 
Not AFAIK

> Do we have any concrete plans to support no-std?
Nothing really concrete

2023-07-07 21:43 UTC, francesca64 commented on rust/Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
I don't think the benefits outweigh the surprise then.

2023-07-07 21:51 UTC, conectado commented on rust/Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
Alright, will change this in a separate PR

2023-07-10 19:39 UTC, francesca64 commented on rust/connlib/libs/tunnel/src/control_protocol.rs
> +                                // We are already on an error state, we ignore if the close errors also
Wouldn't it still be good to log any errors?

2023-07-10 21:41 UTC, francesca64 approved these changes

2023-07-10 23:04 UTC, merged