feat(elixir): use RUN caches
firezone/firezone pull request #2168
Opened 2023-09-27 04:28 UTC by thomaseizinger

In my local testing using the docker-compose file, I had to rebuild the containers several times which always takes quite a while if the commands don't have access to a build cache.

I think there are probably more ways of optimising this Dockerfile. For example, using these caches it is usually not necessary to compile the dependencies separately from the apps because it behaves as an incremental build without docker if anything changes.

I don't know the ins and outs of elixir though so I didn't want to touch that bit but very likely, this can probably just be combined into a single(?) `RUN` step that downloads and compiles the request app.

2023-09-27 04:29 UTC, thomaseizinger commented on elixir/Dockerfile
> +RUN --mount=type=cache,target=./_build cp -r /app/_build/${MIX_ENV}/rel/${APPLICATION_NAME} /app/${APPLICATION_NAME}
This bit is important, we need to `cp` the final artifacts out of the cache, otherwise the next container can't access them.

2023-09-27 04:39 UTC, thomaseizinger commented
@AndrewDryga I saw that you have some volumes going on as well to cache build artifacts. This PR likely is not sufficient to replace all of that but it could be a direction worthwhile exploring to simplify the cache setup.

2023-09-27 15:03 UTC, jamilbk commented
Thank you for adding this! FWIW the elixir devs usually just run the `postgres` service with docker-compose and then start the vanilla Elixir services with `mix phx.server` from the `elixir/` directory. This is because we're on macOS where there's a non-trivial performance hit for going across the filesystem barrier though.

2023-09-27 16:16 UTC, AndrewDryga approved these changes

2023-09-27 16:20 UTC, AndrewDryga requested changes
Just realized that it's not a good idea to do so. 

We can build containers for different architectures and the caches should not be reused between them - it will affect our production containers too and we don't want them to pick up whatever is left after compiling tests on CI. 

This will also be problematic if the Elixir version within docker is not exactly the same as on the host (eg. MacOS can lag behind due to some arm bugs).

So having cache for builds is nice but we definitely don't want to pick up the host cache.

2023-09-27 18:53 UTC, jamilbk commented
@AndrewDryga D'oh, you're completely right, I forget that the Elixir `_build` dir is not architecture-segregated like `cargo`. @thomaseizinger I'm not sure there's a better approach other than letting Docker cache these layers implicitly.

2023-09-28 02:45 UTC, thomaseizinger commented
I think there are some misunderstandings here :)

1. These RUN caches are managed by docker and are effectively volumes stored in `/var/lib/docker/...`. They **don't** map to equivalent directory on the host machine.
2. I think docker separates these accordingly per architecture if you are building for example a docker ARM image vs a docker x64 image.
3. Docker volumes are not cached in CI so this cache doesn't work there anyway.

The only thing these instructions do is have an implicit volume that is mounted for the RUN step. In other words, if you rebuild the an image, the image is going to find its previous build artifacts and thus complete the RUN step quicker.

2023-09-28 02:52 UTC, thomaseizinger commented
> 2\. I think docker separates these accordingly per architecture. If you are building for example a docker ARM image vs a docker x64 image.

Okay, it doesn't but we can make our own key that uniquely identifies a cache location that should be shared: https://docs.docker.com/engine/reference/builder/#run---mounttypecache

2023-09-28 04:36 UTC, jamilbk commented
@thomaseizinger Apologies, been jumping around a bit too much lately and didn't give this the proper review. I'll defer to @AndrewDryga to do the final pass. In general would be in favor of caching.

2023-09-28 21:08 UTC, AndrewDryga commented
@thomaseizinger if we can split the cache for different architectures for issue (2) - we should be safe :).

2023-09-28 23:42 UTC, thomaseizinger commented
> @thomaseizinger if we can split the cache for different architectures for issue (2) - we should be safe 👍 .

Okay, I'll have a play with it! Should I also attempt to combine the different RUN steps where we currently compile dependencies first etc? Also, I saw that the docker-compose file has certain volumes mounted. Are those only for build caches too?

2023-09-29 03:12 UTC, AndrewDryga commented
@thomaseizinger Those volumes are mounted for a container where Elixir code is not going through the release cycle, which is intended to be a local debugging tool. In theory it will allow you to change files on host and live-reload code inside of the container but I never tested it.

> Should I also attempt to combine the different RUN steps where we currently compile dependencies first etc?

Those steps are separate intentionally to minimize builder state changes, eg. allowing reusing fetched and compiled deps even if the application code changed.

2023-09-29 06:22 UTC, thomaseizinger commented
> > Should I also attempt to combine the different RUN steps where we currently compile dependencies first etc?
> 
> Those steps are separate intentionally to minimize builder state changes, eg. allowing reusing fetched and compiled deps even if the application code changed.

Right, I figured that. Using a RUN cache serves (almost) the same purpose. It really is just like incremental builds locally which allows you to remove all this complexity from the dockerfile.

2023-10-03 05:21 UTC, closed without merging

2023-10-03 05:22 UTC, thomaseizinger commented
Closing this because docker does not support caching caches :upside_down_face: