connlib: log more details about failed queries
firezone/firezone pull request #2934
Opened 2023-12-15 21:03 UTC by conectado

2023-12-15 21:22 UTC, ReactorScram commented
Do we have a policy for what info is okay / not okay to log? I was wondering about logging resource URLs / names when doing clipboard copying yesterday and ended up just saying "copied a resource to clipboard"

2023-12-16 01:35 UTC, jamilbk approved these changes

2023-12-16 01:37 UTC, jamilbk commented on rust/connlib/clients/shared/src/control.rs
> +                        tracing::error!(err = ?err, name = query.name, record_type = ?query.record_type, "DNS lookup failed: {err:#}");
```suggestion
                        tracing::debug!(err = ?err, name = query.name, record_type = ?query.record_type, "DNS lookup failed: {err:#}");
```

2023-12-16 01:38 UTC, jamilbk requested changes
Let's not log the DNS names that fail to resolve in they contain anything sensitive. Suggest logging in debug

2023-12-16 01:39 UTC, jamilbk commented
> Do we have a policy for what info is okay / not okay to log? I was wondering about logging resource URLs / names when doing clipboard copying yesterday and ended up just saying "copied a resource to clipboard"

Avoid logging anything sensitive in `info!` or higher levels since that is the default for release clients

2023-12-18 19:31 UTC, conectado commented
> Let's not log the DNS names that fail to resolve in they contain anything sensitive. Suggest logging in debug

I don't think a DNS should ever contain sensitive information also we shouldn't depend on log-level for security

2023-12-19 18:13 UTC, ReactorScram commented
Yeah I suppose if the DNS resources are cleartext in the portal DB then they're not secret. It would only be if there's a glitchy DNS client that puts the whole URL into the request.

2023-12-19 21:56 UTC, jamilbk approved these changes

2023-12-19 22:06 UTC, merged