Roop/fix getting system dns resolvers
firezone/firezone pull request #2967
Opened 2023-12-20 07:59 UTC by roop

Probably fixes #2945.

The adapter keeps track of the system resolver and updates it when the path changes.

When connlib asks for it, it gives the stored system resolver rather than querying at that time (so it doesn't matter that /etc/resolv.conf has the firezone DNS server at that time).

2023-12-20 08:00 UTC, roop commented
For reasons I don't know connlib keeps erroring out ("HTTP error: 422 Unprocessable Entity"), so I'm unable to test this. So, marked as draft.

2023-12-20 18:02 UTC, jamilbk commented
Notes from call: Check whether we can read system default resolvers by setting `matchDomains` to a non-blank string when the tunnel is `reasserting` so that connlib can read the system default resolvers.

2023-12-20 21:39 UTC, jamilbk commented
@roop Just tested the workaround we discussed on the call today. I can verify that applying the following dnsSettings *does not* set our DNS sentinel in `/etc/resolv.conf` and so we can use it to apply to the tunnel in the `reasserting state` so that connlib reads the correct system resolvers.

So something like this before starting connlib:

```
    dnsSettings.matchDomains = ["firezone"]
    dnsSettings.matchDomainsNoSearch = true
```

And then in the `onTunnelReady` you could just set it back to 

```
dnsSettings.matchDomains = [""]
dnsSettings.matchDomainsNoSearch = true
```

You probably want to keep the `matchDomainsNoSearch` to `true` to prevent the dummy domain from ending up as a search domain in /etc/resolv.conf

cc @conectado

2023-12-20 21:40 UTC, jamilbk commented
Another option would be to simply perform the above swap whenever connlib calls `getSystemDefaultResolvers`

2023-12-21 17:18 UTC, jamilbk requested changes
This suffers from the same bug we currently see where unless the `matchDomains` is updated to a non-empty string, `libresolv` will always return connlib's DNS sentinel while the tunnel is instantiated.

2023-12-23 17:49 UTC, jamilbk commented
Superseded by #3012

2023-12-23 17:49 UTC, closed without merging