Use ghcr.io for public pulls of prod images
firezone/firezone pull request #3105
Opened 2024-01-03 20:44 UTC by jamilbk

Noticed our public pulls are coming from `pkg.dev` for prod, so this PR attempts to fix that so that they're from `ghcr.io` to avoid bandwidth fees and segregate public pulls from our own infra pulls.

<img width="463" alt="Screenshot 2024-01-03 at 12 42 51 PM" src="https://github.com/firezone/firezone/assets/167144/22f49996-fe6b-47c7-965f-23d14c9e4e59">

2024-01-03 20:46 UTC, jamilbk commented on terraform/modules/elixir-app/main.tf
> -    {
Not super confident this won't breaking something :😬

2024-01-03 21:17 UTC, AndrewDryga requested changes
You don't need all the Elixir changes and Terraform change will break everything trying to pull from Docker Hub. What you actually want to do is:

1. Keep your change that removes `DOCKER_REGISTRY` from `elixir-app/main.tf`

2. Add it to the production `main.tf` variables and set it to:
```
# Registry from which the Docker install scripts will pull from
{
      name  = "DOCKER_REGISTRY"
      value = "ghcr.io/firezone/firezone"
    },
```

(here: https://github.com/firezone/firezone/blob/main/terraform/environments/production/main.tf#L531)

3. And still use the Google Artifact Registry on staging:

```
# Registry from which the Docker install scripts will pull from
{
      name  = "DOCKER_REGISTRY"
      value = "${module.google-artifact-registry.url}/${module.google-artifact-registry.repo}"
    },
```

(~same place in staging `main.tf`).

2024-01-03 21:51 UTC, jamilbk commented on terraform/modules/elixir-app/main.tf
> -    {
Fixed

2024-01-03 21:51 UTC, jamilbk commented on terraform/environments/production/main.tf
> +      value = "ghcr.io/firezone"
The repo is org-wide, i.e. `docker pull ghcr.io/firezone/gateway`

2024-01-04 17:30 UTC, AndrewDryga approved these changes

2024-01-04 19:50 UTC, merged