android: Move log controls to Logs section of Settings
firezone/firezone pull request #3315
Opened 2024-01-19 01:42 UTC by jasonboukheir

Fixes #2726

2024-01-20 06:05 UTC, jasonboukheir commented
I'm having some trouble generating log files from the app to test out the log settings. Would adding a file in the log directory manually then deleting it be a useful test? Or are logs just not generated on Android (yet)?

2024-01-23 15:07 UTC, jamilbk requested changes
Just some minor UI things otherwise LGTM

2024-01-23 15:07 UTC, jamilbk commented on kotlin/android/app/src/main/java/dev/firezone/android/features/settings/ui/LogSettingsFragment.kt
> +                        val logSize = "${uiState.logSizeBytes / 1000L} KB"
```suggestion
                        val logSize = "${uiState.logSizeBytes / 1000000L} MB"
```

2024-01-23 15:07 UTC, jamilbk commented on kotlin/android/app/src/main/res/values/strings.xml
> +	<string name="log_settings_title">Logs</string>
```suggestion
	<string name="log_settings_title">Diagnostic Logs</string>
```

2024-01-24 18:57 UTC, jamilbk approved these changes

2024-01-24 19:28 UTC, merged