refactor(ci): extract `setup-tauri` action and generalize Windows builds
firezone/firezone pull request #3702
Opened 2024-02-20 23:56 UTC by ReactorScram

To prepare for imminent Linux Tauri GUI

2024-02-21 20:18 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
👍

2024-02-21 20:27 UTC, jamilbk requested changes
LGTM, just the suggestion to simplify things by using the already -available [`runner.os`](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context)

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: linux
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: macos
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: windows
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +          target_os: ${{ matrix.target_os }}
```suggestion
        if: ${{ runner.os == "Windows" || runner.os == "Linux" }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: linux
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: linux
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: macos
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: macos
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: macos
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: windows
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: windows
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +          target_os: ${{ matrix.target_os }}
```suggestion
        if: ${{ runner.os == "Windows" || runner.os == "Linux" }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: windows
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: windows
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +            target_os: windows
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +          target_os: ${{ matrix.target_os }}
```suggestion
        if: ${{ runner.os == "Windows" || runner.os == "Linux" }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
>          with:
```suggestion
        if: ${{ runner.os == "Windows" || runner.os == "Linux" }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/workflows/_rust.yml
> +          target_os: ${{ matrix.target_os }}
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +    required: true
```suggestion
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +      if: ${{ inputs.target_os == 'linux' }}
```suggestion
      if: ${{ runner.os == 'Linux' }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +      if: ${{ inputs.target_os == 'linux' }}
```suggestion
      if: ${{ runner.os == 'Linux' }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +      if: ${{ inputs.target_os == 'linux' }}
```suggestion
      if: ${{ runner.os == 'Linux' }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +      if: ${{ inputs.target_os == 'linux' }}
```suggestion
      if: ${{ runner.os == 'Linux' }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +      if: ${{ inputs.target_os == 'windows' }}
```suggestion
      if: ${{ runner.os == 'Windows' }}
```

2024-02-21 20:27 UTC, jamilbk commented on .github/actions/setup-tauri/action.yml
> +      if: ${{ inputs.target_os == 'windows' }}
```suggestion
      if: ${{ runner.os == 'Windows' }}
```

2024-02-21 20:34 UTC, ReactorScram commented
@jamilbk Figured there's something like that, I should have asked ChatGPT lol
I'm also going to ditch the `target` for `setup-rust` whenever possible, because it already picks MSVC on Windows and GNU on Linux, which is what I want it to do.

2024-02-21 20:57 UTC, ReactorScram commented on .github/workflows/_rust.yml
> +    name: gui-smoke-test-${{ matrix.runs-on }}
For some reason `runner.os` wasn't working in `name` keys

2024-02-22 00:42 UTC, jamilbk approved these changes

2024-02-22 00:52 UTC, ReactorScram commented
@jamilbk Since the test names changed, this might have a similar problem with branch protection as we had a few weeks ago on some other PR. 

I see Github is waiting for `build-tauri-windows-client` and `windows-smoke-test`, those are now `build-gui-windows-2019`, `gui-smoke-test-windows-2019`, and `gui-smoke-test-windows-2022`

2024-02-22 02:08 UTC, merged