docs: Linux GUI client
firezone/firezone pull request #4965
Opened 2024-05-12 18:13 UTC by jamilbk

Draft because it's almost certainly missing information or partially inaccurate. I don't have a x64 linux desktop readily available for testing.

2024-05-13 14:27 UTC, ReactorScram requested changes
I left some notes on Vercel. The biggest thing is that this script should be translated to human instructions somehow, since this is what I've been testing with:

https://github.com/firezone/firezone/blob/0f112e0e699dc7e8609c7496b19fbf13bd213137/scripts/firezone-client-gui-install.sh

~~To un-install, stopping the GUI and doing `apt-get remove firezone-$WHATEVER` should suffice.~~
See this PR https://github.com/firezone/firezone/blob/fad86babd7fff13f7628936a1a804f02d43c3b34/rust/gui-client/docs/intended_behavior.md#un-install-checklist-linux

2024-05-13 14:27 UTC, ReactorScram commented on website/src/app/kb/user-guides/linux-gui-client/readme.mdx
> +menu or by running `firezone-client-gui` from an interactive shell.
You have to add yourself to the group and reboot too. I could not get the group-add step to work with merely logging out and back in https://github.com/firezone/firezone/blob/0f112e0e699dc7e8609c7496b19fbf13bd213137/scripts/firezone-client-gui-install.sh

The group must exist (Line 17 creates it) before the systemd service can start, since it refers to the group.

2024-05-15 21:44 UTC, ReactorScram commented on website/pnpm-lock.yaml
I did `pnpm install` since I didn't have the `node_modules` dir, not sure if the lock file was supposed to update?

2024-05-15 21:47 UTC, ReactorScram commented on website/src/app/kb/user-guides/linux-gui-client/readme.mdx
> +The Linux GUI Client is to designed for Linux desktop environments where a
```suggestion
The Linux GUI Client is designed for Linux desktop environments where a
```

2024-05-15 22:21 UTC, jamilbk commented on website/pnpm-lock.yaml
I don't _think_ so, but it could? You might want `--frozen-lockfile`

https://pnpm.io/cli/install#tldr

2024-05-15 22:22 UTC, jamilbk commented on website/pnpm-lock.yaml
That TLDR section is nice. Maybe we should have a TL;DR at the top of all of our docs.

2024-05-16 15:39 UTC, ReactorScram commented on website/pnpm-lock.yaml
It's considered a good thing: https://en.wikipedia.org/wiki/BLUF_(communication)

People don't read prose. 

Beginners won't understand it, and experts won't need it. So for installs and upgrades we could just put the Bash commands up top with either in-line comments or a brief prose explanation below it.

"I have a secret for making web pages load fast - Make sure the essential content loads and renders first. Then, don't do anything, you're done."

2024-05-16 15:48 UTC, ReactorScram commented
Closing, combining with #5007

2024-05-16 15:48 UTC, closed without merging