fix(style): Set prettier prosewrap to 'never' to enforce one paragraph per line
firezone/firezone pull request #5722
Opened 2024-07-04 16:31 UTC by jamilbk

Prettier has three options for prose-wrap:

- `always`: Format prose (markdown) to the line-length (current)
- `never`: Use a single line for all prose (proposed)
- `preserve`: Don't lint prose

I would be OK with (1) or (2), but option (3) means we won't have things like double spaces or other whitespace issues automatically cleaned up in our docs and marketing website, so I'd prefer not to choose that option.

2024-07-04 16:43 UTC, AndrewDryga approved these changes

2024-07-04 16:47 UTC, jamilbk commented
Adding others for review just in case anyone has strong opinions on the matter.

2024-07-05 05:43 UTC, thomaseizinger approved these changes
Thank you! I much prefer that.

I'll send a follow-up PR to break the sentences in my blog post into individual lines.

2024-07-05 05:51 UTC, jamilbk commented
> Thank you! I much prefer that.
> 
> I'll send a follow-up PR to break the sentences in my blog post into individual lines.

Just remember this will make them individual paragraphs in markdown. So this effectively means 1 paragraph per line, not 1 sentence per line.

2024-07-05 10:22 UTC, thomaseizinger commented
> > Thank you! I much prefer that.
> > I'll send a follow-up PR to break the sentences in my blog post into individual lines.
> 
> Just remember this will make them individual paragraphs in markdown. So this effectively means 1 paragraph per line, not 1 sentence per line.

That is not true in my observation. Markdown creates new paragraphs for double newlines, not individual ones.

2024-07-05 13:24 UTC, jamilbk commented
> > > Thank you! I much prefer that.
> > > I'll send a follow-up PR to break the sentences in my blog post into individual lines.
> > 
> > 
> > Just remember this will make them individual paragraphs in markdown. So this effectively means 1 paragraph per line, not 1 sentence per line.
> 
> That is not true in my observation. Markdown creates new paragraphs for double newlines, not individual ones.

Right -- what I mean is prettier will collapse those into a single line upon formatting.

2024-07-05 15:05 UTC, ReactorScram requested changes, later dismissed
I skimmed through it and only found that one case where it messed up the underscores

2024-07-05 15:05 UTC, ReactorScram commented on elixir/apps/web/assets/vendor/heroicons/LICENSE.md
It won't be a problem that the licenses aren't verbatim anymore, right? Can we have prettier ignore those, or will GitHub and those auto-license-detect tools pick them up either way?

2024-07-05 15:05 UTC, ReactorScram commented on rust/gui-client/docs/intended_behavior.md
> +1. Expect the zip file to start with "firezone*logs*"
😨

2024-07-05 15:05 UTC, ReactorScram commented on rust/headless-client/README.md
> +1. Set `FIREZONE_ID` to a unique string to identify this client in the portal, e.g. `export FIREZONE_ID=$(uuidgen)`. The client requires this variable at startup.
I think this is handled automatically, opened #5756 to fix that in a separate PR

2024-07-05 15:05 UTC, ReactorScram commented on website/src/app/blog/enterprises-choose-open-source/readme.mdx
> +While open source may have gotten an [unconventional start](https://en.wikipedia.org/wiki/Open-source-software_movement#:~:text=Brief%20history,-Further%20information%3A%20Open&text=The%20label%20%22
Nit 
```suggestion
While open source may have gotten an [unconventional start](https://en.wikipedia.org/wiki/Open-source-software_movement#Brief_history) from hackers, visionaries and technologists, the benefits are clear. It’s being used to modernize and standardize IT infrastructure, security, scalability, and application development. Open source is now a preferred development strategy for large and small organizations from cloud providers to security solutions and beyond.
```

Firefox doesn't support those kinds of links (last time I checked anyway), and I'm guessing it will break if the text changes

2024-07-05 15:06 UTC, ReactorScram commented on rust/gui-client/docs/intended_behavior.md
> +1. Expect the zip file to start with "firezone*logs*"
```suggestion
1. Expect the zip file to start with `firezone_logs_`
```

2024-07-05 15:12 UTC, bmanifold commented
I haven't written a large amount of prose in our repo, so I don't have a strong preference here.  It does feel slightly strange to have each paragraph on one line.  Editing that feels like it will be a pain, but without having done it I can't say for sure.

Would this problem be solved (or at least mostly solved) if the writer set their editor to have a hard wrap at the same length of our prettier config when writing prose?

> Google Docs has pretty good history tracking for prose writing.

I think this could be a good alternative too.

2024-07-05 15:15 UTC, ReactorScram commented
The downside to Google Docs is that I don't think you can access the files ever. Only import and export from other formats.

2024-07-05 15:25 UTC, jamilbk commented on rust/gui-client/docs/intended_behavior.md
> +1. Expect the zip file to start with "firezone*logs*"
Woah, nice catch! This is probably a function of running prettier on this, and not specifically the prose wrap effect.

2024-07-05 21:33 UTC, thomaseizinger commented
> > > > Thank you! I much prefer that.
> > > > I'll send a follow-up PR to break the sentences in my blog post into individual lines.
> > > 
> > > 
> > > Just remember this will make them individual paragraphs in markdown. So this effectively means 1 paragraph per line, not 1 sentence per line.
> > 
> > 
> > That is not true in my observation. Markdown creates new paragraphs for double newlines, not individual ones.
> 
> Right -- what I mean is prettier will collapse those into a single line upon formatting. There is no option to preserve one sentence per line -- when you try to do that, they'll be collapsed.

Oh, that is a bit disappointing. I am less inclined to merge this then because it just creates churn.

> Would this problem be solved (or at least mostly solved) if the writer set their editor to have a hard wrap at the same length of our prettier config when writing prose?

Applying prettier to the output isn't so much the issue. It is reading and editing the markdown source. For example, when you proof read the text you want to look at the rendered version. Linking that back to the source is tricky because lines don't mean anything with hard wrapping. You can scan the code for "The sentence that starts with XYZ" because sentences are not lines.

Similarly, GitHub's suggestions work line-by-line. Collabrating on the post here in a PR review is much easier if you can just accept suggestions.

Lastly, good prose doesn't have long sentences. If you have one sentence per line, you are being reminded about that during writing (and editing).

2024-07-05 21:50 UTC, jamilbk commented
Let's do this -- let's just use `preserve`, and we can write markdown prose however we want. I'll up the PR.

2024-07-05 22:45 UTC, bmanifold commented
>Applying prettier to the output isn't so much the issue. It is reading and editing the markdown source. For example, when you proof read the text you want to look at the rendered version. Linking that back to the source is tricky because lines don't mean anything with hard wrapping. You can't scan the code for "The sentence that starts with XYZ" because sentences are not lines.

>Similarly, GitHub's suggestions work line-by-line. Collabrating on the post here in a PR review is much easier if you can just accept suggestions.

>Lastly, good prose doesn't have long sentences. If you have one sentence per line, you are being reminded about that during writing (and editing).

In reading all of this, it feels to me like we may just be using the wrong tool for the job.  Using Google Docs for example would allow you to bypass all of this.  Everything you type would be in it's final format.  It would allow people to make suggestions that can be accepted with a push of a button.  It would also allow people to make comments on specific sections of text.  It may introduce other problems, but it does seem to solve the problems being discussed.

I also recognize that there likely won't be a perfect solution here and I'm also ok with just using the `preserve` option.

2024-07-05 23:22 UTC, thomaseizinger commented
> > Applying prettier to the output isn't so much the issue. It is reading and editing the markdown source. For example, when you proof read the text you want to look at the rendered version. Linking that back to the source is tricky because lines don't mean anything with hard wrapping. You can't scan the code for "The sentence that starts with XYZ" because sentences are not lines.
> 
> > Similarly, GitHub's suggestions work line-by-line. Collabrating on the post here in a PR review is much easier if you can just accept suggestions.
> 
> > Lastly, good prose doesn't have long sentences. If you have one sentence per line, you are being reminded about that during writing (and editing).
> 
> In reading all of this, it feels to me like we may just be using the wrong tool for the job. Using Google Docs for example would allow you to bypass all of this. Everything you type would be in it's final format. It would allow people to make suggestions that can be accepted with a push of a button. It would also allow people to make comments on specific sections of text. It may introduce other problems, but it does seem to solve the problems being discussed.

I am open to using Google Docs too but what does that mean for our blog posts? Convert them to markdown just before we publish? Is there a markdown export for Google Docs?

It is also not fully ideal. @jamilbk and I iterated on the post with several PRs after it was merged.

2024-07-05 23:25 UTC, thomaseizinger commented
> Let's do this -- let's just use `preserve`, and we can write markdown prose however we want. I'll up the PR.

Sounds good to me. That is less intrusive as well because we don't need to reformat anything of the existing code.

2024-07-07 00:32 UTC, jamilbk commented
> > Applying prettier to the output isn't so much the issue. It is reading and editing the markdown source. For example, when you proof read the text you want to look at the rendered version. Linking that back to the source is tricky because lines don't mean anything with hard wrapping. You can't scan the code for "The sentence that starts with XYZ" because sentences are not lines.
> 
> > Similarly, GitHub's suggestions work line-by-line. Collabrating on the post here in a PR review is much easier if you can just accept suggestions.
> 
> > Lastly, good prose doesn't have long sentences. If you have one sentence per line, you are being reminded about that during writing (and editing).
> 
> In reading all of this, it feels to me like we may just be using the wrong tool for the job. Using Google Docs for example would allow you to bypass all of this. Everything you type would be in it's final format. It would allow people to make suggestions that can be accepted with a push of a button. It would also allow people to make comments on specific sections of text. It may introduce other problems, but it does seem to solve the problems being discussed.
> 
> I also recognize that there likely won't be a perfect solution here and I'm also ok with just using the `preserve` option.

Yeah I sometimes prefer brainstorming / collaborating in google docs. But then it has to go into MDX, and then edits usually are made at some point then. I suppose the line between the two isn't so clear.

2024-07-07 12:39 UTC, thomaseizinger approved these changes
LGTM

PR description could use an update to track the new decision.

2024-07-08 14:06 UTC, ReactorScram approved these changes

2024-07-08 14:41 UTC, merged