Show user on admin devices table
firezone/firezone pull request #598
Opened 2022-05-16 04:30 UTC by princemaple

![image](https://user-images.githubusercontent.com/1329716/168519950-fbb0adfb-3e18-402c-85a6-ea093b607519.png)

2022-05-16 12:24 UTC, princemaple commented on apps/fz_http/lib/fz_http/devices.ex
> +    Repo.all(from Device, preload: :user)
actually I'm going to change it to preload in the live view tomorrow.

credo is affecting my judgement... I went too far to avoid some warnings.

2022-05-17 00:06 UTC, princemaple commented
This is ready for review

2022-05-17 18:33 UTC, jamilbk requested changes
@princemaple Looks good! Could you add a simple test in `apps/fz_http/test/fz_http_web/live/device_live/admin/index_test.exs`?

2022-05-17 18:33 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/templates/shared/devices_table.html.heex
> +          <%= device.user.email %>
Could you make this a link to `Routes.user_show_path/2`?

2022-05-18 02:18 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/templates/shared/devices_table.html.heex
> +          <%= link(device.user.email, to: Routes.user_show_path(@socket, :show, device.user)) %>
👍

2022-05-18 02:19 UTC, jamilbk commented on apps/fz_http/test/fz_http_web/live/device_live/admin/index_test.exs
> +        assert html =~ device.user.email
👍

2022-05-18 02:19 UTC, jamilbk commented
LGTM! Will merge when pipeline settles

2022-05-18 03:04 UTC, jamilbk approved these changes

2022-05-18 03:04 UTC, merged