Sync users with OIDC provider
firezone/firezone pull request #605
Opened 2022-05-17 01:24 UTC by princemaple

WIP

2022-05-17 09:39 UTC, princemaple commented
Given that we go the refresh token route. Some notes.

Refresh Token:
- Google gives it to you by default
  - although it says you need to specify `access_type: offline`, it actually doesn't care
- Okta takes a `offline_access` scope
- I imagine most others will be like this 2. If the user uses one that requires a scope, we need to state clearly that they need to find out what the scope required is.

Implementation:
- config `refresh_interval`
- Store `refresh_token_provider`, `refresh_token`, `refreshed_at` on user, assuming there is always only 1 identity provider is being used, on a separate table if otherwise
- use GenServer to periodically send refresh request, if `refreshed_at` + `refresh_interval` is in the past for the user
- use the `refresh_token` type instead of `authorization_token` when requesting for `access_token`

Q:
- What needs to be done to achieve "Disable user VPN sessions", remove all devices of the user?

cc @jamilbk @mdp

2022-05-17 17:42 UTC, jamilbk commented
@princemaple

Yeah, seems like requesting a `refresh_token` + `access_token` and then periodically requesting a new `access_token` in the background seems like the best way to accomplish this, assuming the OIDC provider fails the request if the user is removed / disabled in their system.

+1 on using a GenServer with a periodic timer for this (I use this pattern in a couple places). Maybe spawn a GenServer for each user or each OIDC provider since they may have different rate limits / error reporting?

Maybe we should track `refresh_token_response` as well? It would be helpful to save the refresh response body and status code in case an administrator wants to debug.

Hmm, I'll have to think about what multiple OIDC providers means for refresh tokens, but it's kinda feeling like this should be in its own table anyway. It'll help keep modules smaller and easier to test, easier to reason about, more secure, etc.

To disable VPN sessions, see here: https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/devices.ex#L91

I check for which devices to (i.e. WireGuard peer public keys) to apply to the server WireGuard interface every minute, and if a user's VPN session has expired I simply omit their devices' public key from being added to the interface.

2022-05-18 05:33 UTC, princemaple commented
A couple updates:

1. Google does need the `access_type: "offline"` after all, despite the internet (SO) and the google oauth playground both say otherwise, at least when signing in from the web prompt
2. Refresh token is only granted the very first time you sign in (at least for google). We will need to let the users know that they have to reconfigure their oauth, or revoke all current users and let them sign in again. @jasonboukheir 

Progress:

1. oidc/oauth is pretty well designed I guess. I can simply reuse the `fetch_tokens` from `:openid_connect` with some overriding params, like so:
```elixir
OpenIDConnect.fetch_tokens(
  :google,
  %{grant_type: "refresh_token", refresh_token: "REFRESH_TOKEN"}
)
```
This returns `{:ok, refreshed_claims}`

2. I revoked my test app's access to my account, hopefully simulating the same situation when a user is removed from their org. I managed to get a 400.

This returns `{:error, :fetch_tokens, %HTTPoison.Response{status_code: 400}}`

2022-05-19 08:19 UTC, princemaple commented
Ready for a first pass. Functionality is there.

Obviously tests haven't been added. I manually tested against a dummy google project.

2022-05-20 00:53 UTC, jamilbk reviewed
Nice approach! The only gotcha I think we need to be careful of is disabling users if Firezone is offline or has no connectivity for an extended period.

Ah also, we should have some mechanism for an administrator to re-enable an accidentally-disabled user... maybe a UI form?

2022-05-20 00:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/refresher.ex
> +      |> User.changeset(%{last_signed_in_at: ~U[1970-01-01 00:00:00Z]})
Hm, wonder if we should prevent disabling an `admin` user? Maybe if it's the last admin in the system?

2022-05-20 00:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/refresher.ex
> +      |> User.changeset(%{last_signed_in_at: ~U[1970-01-01 00:00:00Z]})
Instead of changing `last_signed_in_at` here, I think we'll probably have to add a `disabled_reason` string on `users` to track disabled Users and check for this in `Devices.to_peer_list/0` since we allow never-signed-in Users to connect to VPN if the adminstrator has not turned on the `Require users to authenticate for VPN` setting.

`disabled_reason` could be set to `oidc_refresh_error` for now. Later down the road we could add more, e.g. `too_many_password_attempts` or `disabled_by_admin` (later down the road).

2022-05-20 00:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/refresh_manager.ex
> +    |> Repo.all()
Maybe this could be optimized to only fetch users that have an associated `oidc_connection`?

2022-05-20 00:53 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/controllers/auth_controller.ex
> +          # only first-time connect will include refresh token
Hmm thinking through this, if Firezone is offline for an extended time, will that disable all OIDC users permanently? Or will it just force them to re-authenticate at the next sign-in?

2022-05-20 01:05 UTC, princemaple commented on apps/fz_http/lib/fz_http/oidc/refresh_manager.ex
> +    |> Repo.all()
Yep, I omitted a lot of optimization, intentionally. As I wasn't sure, what we will do eventually, like having a manager per site, or per user, or per site per user, or per site per provider, etc.

2022-05-20 01:06 UTC, princemaple commented on apps/fz_http/lib/fz_http/oidc/refresher.ex
> +      |> User.changeset(%{last_signed_in_at: ~U[1970-01-01 00:00:00Z]})
Admins don't get disconnected either way, but if the point was to not change their last logged in time, the point is valid.

2022-05-20 01:06 UTC, princemaple commented
@jamilbk 

Being offline is not a problem. Even though it's called `refresh_token`. it doesn't necessarily refresh. It either gets you a new `access_token`, or returns your old access_token but reactivated, depending on the implementation of the provider. I didn't need to send an old `access_token` alongside to get a new one, from google.

`disable_reason` sounds good. However, seeing `disabled_by_admin`, I think the semantics here is a little vague. Can a disabled user log into the system? Or are they simply not allowed to connect their VPN? The current `last_signed_in_at` approach only disables the VPN usage. Users can sign in as usual.

2022-05-20 01:13 UTC, princemaple commented on apps/fz_http/lib/fz_http/oidc/refresher.ex
> +      |> User.changeset(%{last_signed_in_at: ~U[1970-01-01 00:00:00Z]})
> Ah also, we should have some mechanism for an administrator to re-enable an accidentally-disabled user... maybe a UI form?

They could add the user back to their OIDC provider? If you meant not using an OIDC login, I guess they can remove the user's OIDC connection - then they will not be checked, hence won't be disabled.

2022-05-20 01:20 UTC, jamilbk commented
> The current last_signed_in_at approach only disables the VPN usage.

I think only disabling VPN makes sense. My point was that with the "Require Authentication for VPN Sessions" set to `Never` or `Once`, I'm not sure changing the `last_signed_in_at` will actually disable their VPN session?

<img width="686" alt="Screen Shot 2022-05-19 at 6 18 40 PM" src="https://user-images.githubusercontent.com/167144/169429465-eec08d40-8c63-45f1-ae56-fb68563c9531.png">

2022-05-20 01:21 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/refresh_manager.ex
> +    |> Repo.all()
Sounds good.

2022-05-20 01:29 UTC, princemaple commented
> My point was that with the "Require Authentication for VPN Sessions" set to `Never` or `Once`, I'm not sure changing the `last_signed_in_at` will actually disable their VPN session?

Ah right. Didn't think about this. OK so we need a way to disable a user's session without relying on the `last_signed_in_at` field. This is actually better and more reliable.

So, the last thing is working out what we do with the disable reason. `too_many_password_attempts` would lock out the user from signing in. Do you think we need `disable_vpn_reason` and `disable_login_reason`?

2022-05-20 01:36 UTC, jamilbk commented
Hmmm could probably just use `oidc_refresh_failed`? I guess it'd be easy to change later with a migration so not too picky.

2022-05-20 01:48 UTC, princemaple commented
Sure. Get it going first. 👍

2022-05-20 23:24 UTC, princemaple commented
Can use a second pass.

Now uses `allowed_to_connect` field.
Admins can toggle this field on User#Index and User#Show.

![image](https://user-images.githubusercontent.com/1329716/169624082-d17036ca-f963-4dfc-8087-9945818e25f7.png)

2022-05-21 05:45 UTC, princemaple commented
![image](https://user-images.githubusercontent.com/1329716/169637616-cf4d766b-8ffb-471f-8039-a4adf400d7a9.png)

2022-05-23 21:25 UTC, jamilbk requested changes
Looks good, just a few suggestions. Also, a couple design improvements I think we should consider:

* What do you think of refactoring `allowed_to_connect:boolean` to `disabled_at:datetime` field?
* Should probably re-allow VPN sessions after a user successfully authenticates in `Authentication.sign_in/2`
* Should probably disconnect user_sockets related to the user when they get disabled... prevents an admin from Re-enabling their own VPN connection from a connected browser tab

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/refresher.ex
> +      Logger.info("Disabling user\##{user_id}...")
May want to state why here and log the email instead of user_id? , e.g.

```elixir
Logger.info("Disabling user #{user.email} due to OIDC token refresh failure...")
```

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/refresher.ex
> +
Could you add a new [telemetry function](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/telemetry.ex) and call it here to track events like this?

```elixir
def disable_user(user, reason = "oidc refresh failure") do
      telemetry_module().capture(
      "disable_user",
      common_fields() ++
        [
           user_email_hash: hash(user.email),
           reason: reason
        ]
    )
end
```

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex
> +    user =
Could you call the new telemetry function here too?

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/templates/shared/user_details.html.heex
> +    <tr>
Hmmm, maybe we should make this non-editable? I wonder if Admins will need to do this en-masse, we might not want to make it this easy for admins to accidentally enable/disable VPN connections.

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/user_live/index.html.heex
> +          <td>
What do you think about moving this down to the `Danger Zone` section below? It feels like enabling / disabling a user's VPN should come with a bit more thought.

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/user_live/index.html.heex
> +          <th>Can Connect</th>
See comment Re: moving this down to the section below.

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex
> +    <input type="checkbox" phx-target={@myself} disabled={@user.role == :admin}
Thoughts on adding `data-confirm="Are you sure? This may affect this user's internet connectivity."`

2022-05-23 21:25 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/user_live/allowed_to_connect_component.ex
> +    <input type="checkbox" phx-target={@myself} disabled={@user.role == :admin}
Thoughts on adding `data-confirm="Are you sure? This may this user's internet connectivity."`

2022-05-25 06:03 UTC, princemaple commented
Can use a final review if this one goes green.

2022-05-25 08:12 UTC, princemaple commented
> Should probably disconnect user_sockets related to the user when they get disabled... prevents an admin from Re-enabling their own VPN connection from a connected browser tab

Note: Disconnected user can still reconnect, as they are not signed out. Do we have a way to sign out a user? (i.e. is the user session persisted on server and can be cleared)

2022-05-25 15:58 UTC, jamilbk commented
> > Should probably disconnect user_sockets related to the user when they get disabled... prevents an admin from Re-enabling their own VPN connection from a connected browser tab
> 
> Note: Disconnected user can still reconnect, as they are not signed out. Do we have a way to sign out a user? (i.e. is the user session persisted on server and can be cleared)

No, the user session is persisted only via cookies and signed out via `Authentication.sign_out/1`. Hmm good catch on this. I think what we probably want to do is prevent disabled users from being loaded from the cookie on each page request. Currently, users are loaded [using `Guardian.Plug.LoadResource` here](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/authentication/pipeline.ex#L14). I'm thinking we can add our own custom plug that after the `VerifySession` plug but before the `LoadResource` plug that checks to see if the user being loaded has `disabled_at` set?

2022-05-25 19:49 UTC, princemaple commented
There is code that makes admin VPN sessions never expire. Should it change now or stay the same?

Given that the auto logout is really only against admins. Unprivileged users don't have the ability to grant permission for themselves, even if they can still logon.

2022-05-25 19:51 UTC, jamilbk commented
> There is code that makes admin VPN sessions never expire. Should it change now or stay the same?

Let's change it to make admins subject to expiration too.

2022-05-25 19:54 UTC, jamilbk commented
> Given that the auto logout is really only against admins. Unprivileged users don't have the ability to grant permission for themselves, even if they can still logon.

I think with 4 hour cookie sessions, we can accept this edge case for now -- maybe we can add a config option for this in the future: `disable user login to the web portal if removed from OIDC`.

2022-05-26 00:57 UTC, princemaple commented
Updated PR description

2022-05-26 05:37 UTC, jamilbk commented on apps/fz_http/test/support/test_helpers.ex
> +  def create_users(opts) do
Thanks :-)

2022-05-26 05:38 UTC, jamilbk approved these changes
LGTM! This is awesome. Nice work!

2022-05-26 05:42 UTC, jamilbk commented
cc @gongjason

Two in this PR for you to be aware of:

- new telemetry event: `disable_user`, which contains `user_email_hash` and `reason` fields. Disabled users can no longer connect to VPN
- Changes to how OIDC works -- if a token refresh fails for whatever reason, the user can't connect to VPN (this is useful for disabling a user's VPN when removed from OIDC provider)

2022-05-26 05:43 UTC, merged

2022-05-26 05:59 UTC, princemaple commented
@gongjason and this:
> Store OIDC connection (mainly the refresh token) when user login via an OIDC provider. This can only be done when they sign in via their chosen provider the very first time. Existing users will have to revoke their access on the provider and re-login.

2022-06-09 14:37 UTC, luong-komorebi commented
For everyone who just upgrade to 0.3.16 for this feature, please read the the documents for 0.4 [in this commit](https://github.com/firezone/firezone/blob/dac6b5aac4b471826439fe2b236a4e1ec38e8842/docs/docs/authenticate/google.md)

For this feature to work, you will need to
1. Update the callback URL. It should end with `/auth/oidc/<provider_key>/callback/` 
2. Update the scope of the oauth app/client to include scopes that allow OIDC and refresh tokens

2022-10-31 11:23 UTC, alikhil commented
Hi!

Does this feature work with keycloak?