Docs - OIDC instructions (WIP)
firezone/firezone pull request #615
Opened 2022-05-17 23:09 UTC by gongjason

- added Azure aD
- updated Google + Okta

2022-05-17 23:25 UTC, princemaple commented
Should we add it now or later:

Google gives you `refresh_token` no matter what
Microsoft and Okta requires `offline_access` scope to get the `refresh_token`

They will be required for the auto disable functionality.

2022-05-18 00:45 UTC, gongjason commented
@princemaple it prob makes sense to add it together with the auto-disable functionality (if it isn't merged yet). It's pretty easy to update scopes/permissions for Azure/Okta.

2022-05-18 02:14 UTC, princemaple commented
Nah it's not merged. It's going to take while to finish. Cool. I just thought that it'd be a widely wanted feature so users might as well get ready for it already.

2022-05-19 00:03 UTC, jamilbk commented on docs/docs/authenticate/azure-ad.md
> +1. `redirect_uri`: Instructs OIDC identity provider where the response to the
clarif:

```
1. `redirect_uri`: Instructs OIDC provider where to redirect after authentication. Should be your firezone `EXTERNAL_URL + /auth/oidc/<provider_key>/callback`, e.g. `https://firezone.example.com/auth/oidc/azure/callback`
```

2022-05-19 00:16 UTC, jamilbk commented on docs/docs/authenticate/azure-ad.md
> +1. `scope`: The permissions required by Firezone.
suggested technical clarification:

```
1. `scope`: [OIDC scopes](https://openid.net/specs/openid-connect-basic-1_0.html#Scopes) to obtain from your OIDC provider. This should be set to `openid email` to provide Firezone with the user's email in the returned claims.

2022-05-19 00:26 UTC, jamilbk commented on docs/docs/authenticate/index.md
> +through an OIDC identity provider. The configuration file can be found at
nit: `OIDC identity provider` -> `OIDC provider`. I think this is the commonly used terminology around the web. `OIDC consumer` would be Firezone

2022-05-19 00:26 UTC, jamilbk commented on docs/docs/authenticate/index.md
> +  google: [
`[` should be `{`

2022-05-19 00:27 UTC, jamilbk commented on docs/docs/authenticate/index.md
> +  ]
should be `}`

2022-05-19 00:27 UTC, jamilbk commented on docs/docs/authenticate/index.md
> +identity providers:
nit: `OIDC providers` ?

2022-05-19 00:27 UTC, jamilbk commented on docs/docs/authenticate/index.md
> +identity providers:
Ah nvmd, I see now

2022-05-19 00:30 UTC, jamilbk commented on docs/docs/authenticate/google.md
> +  google: [
`[` -> `{`

2022-05-19 00:30 UTC, jamilbk commented on docs/docs/authenticate/google.md
> +  ]
`]` -> `}`

2022-05-19 00:31 UTC, jamilbk commented on docs/docs/authenticate/google.md
> +(Google, Okta, Dex) to be used for authetication._
typo: `authetication`

2022-05-19 00:35 UTC, jamilbk commented on docs/docs/authenticate/google.md
> +
Maybe add a paragraph here strongly encouraging users to update to the new generic OIDC provider format?

> We strongly recommending transitioning your existing Google or Okta-based SSO configuration to the generic OIDC-based configuration format described here. We'll be removing the Google-specific and Okta-specific SSO functionality in a future release.

2022-05-19 00:37 UTC, jamilbk commented on docs/docs/authenticate/azure-ad.md
> +1. `scope`: The permissions required by Firezone.
Nevermind, we can leave `profile` in there as it's fairly common and will be useful for sending outbound emails.

2022-05-19 00:38 UTC, jamilbk requested changes
Just some minor nitpicks and typos!

2022-05-19 01:25 UTC, gongjason commented on docs/docs/authenticate/index.md
> +through an OIDC identity provider. The configuration file can be found at
👍  good to know!

2022-06-09 18:06 UTC, jamilbk commented on docs/docs/administer/upgrade.md
> +integration after upgrading.
How does one re-setup the OIDC integration? I think we may get some confused users here. Either the Oauth app needs to be completely removed and recreated (new client_id and client_secret) or the user needs to revoke the permissions for the app (I think this varies on a case-by-case).

Option (1) is the one that should work in most cases.

2022-06-11 03:05 UTC, gongjason commented on docs/docs/administer/upgrade.md
> +### I have an existing OIDC integration
@jamilbk @princemaple what do you think about this?

2022-06-11 03:06 UTC, gongjason commented on docs/docs/administer/upgrade.md
> +[create a new app integration]({%link docs/authenticate/index.md%}).
@princemaple @jamilbk what do you think about this?

2022-06-13 09:37 UTC, princemaple commented on docs/docs/administer/upgrade.md
> +[create a new app integration]({%link docs/authenticate/index.md%}).
Maybe worth a mention that they can turn on the site wide expiry (if they were set to Never previously), so they can make sure that the removed users are properly handled.

2022-06-13 15:37 UTC, jamilbk approved these changes
Looks awesome, very detailed and clear. Much much improved, thanks!

2022-06-13 15:37 UTC, jamilbk commented on docs/docs/administer/upgrade.md
> +[create a new app integration]({%link docs/authenticate/index.md%}).
I think this is clear enough. Let's go with this and if we get any confusion around this we can add more clarification here.

2022-06-13 15:38 UTC, merged