fix(website): Animate sliding customer logos, fix action link styling
firezone/firezone pull request #6309
Opened 2024-08-15 20:16 UTC by Patticatti

2024-08-15 20:57 UTC, jamilbk requested changes

2024-08-15 20:57 UTC, jamilbk commented on website/src/components/CustomerLogos/index.tsx
> +            className="  "
```suggestion
```

2024-08-15 20:58 UTC, jamilbk commented
Looks like CI is failing for the `globals.css` file:

https://github.com/firezone/firezone/actions/runs/10409951593/job/28830709460?pr=6309#step:7:43

Needs a `prettier` run on it.

2024-08-15 21:14 UTC, jamilbk commented
- I think some of the logos are cutoff now
- The space between the last logo and first logo is not consistent
- Any chance this could be slowed down by at least half?

<img width="605" alt="Screenshot 2024-08-15 at 2 13 30 PM" src="https://github.com/user-attachments/assets/53673507-7151-4921-b93b-0b91030c80c9">
<img width="244" alt="Screenshot 2024-08-15 at 2 13 15 PM" src="https://github.com/user-attachments/assets/1270fc14-5c15-4c8c-b16a-39f6e6c79a48">

2024-08-20 05:52 UTC, Patticatti commented
> * I think some of the logos are cutoff now
> * The space between the last logo and first logo is not consistent
> * Any chance this could be slowed down by at least half?
> 
> <img alt="Screenshot 2024-08-15 at 2 13 30 PM" width="605" src="https://private-user-images.githubusercontent.com/167144/358397315-53673507-7151-4921-b93b-0b91030c80c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzM0MTQsIm5iZiI6MTcyNDEzMzExNCwicGF0aCI6Ii8xNjcxNDQvMzU4Mzk3MzE1LTUzNjczNTA3LTcxNTEtNDkyMS1iOTNiLTBiOTEwMzBjODBjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNTUxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTJhMTRhMTYwN2VhODQ4MDM1YzYzNjhlNDk4Y2M4ZDY1MDUxYzlkNDU4ZGZhMjIxMjlhYjY0ZmI2NGE2MTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MDG0TAm8JVrtHtglX8jUjpdEcStW3V1XLZW2a0vydOU"> <img alt="Screenshot 2024-08-15 at 2 13 15 PM" width="244" src="https://private-user-images.githubusercontent.com/167144/358397320-1270fc14-5c15-4c8c-b16a-39f6e6c79a48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzM0MTQsIm5iZiI6MTcyNDEzMzExNCwicGF0aCI6Ii8xNjcxNDQvMzU4Mzk3MzIwLTEyNzBmYzE0LTVjMTUtNGM4Yy1iMTZhLTM5ZjZlNmM3OWE0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNTUxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjQwOGNlNmRlMDE2ZjgwYWM5NTI0ZjE3ZWVjZDA2NjJjNWRlYzExOTM5ZDYzM2JlZDc1MDI1ZTAwYjVjZDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gMmE9Is1cGJrVyHBUQd7DpMalJ0Tr4Y4LSf-JBTEisk">

Fixed and slowed down a tad, like to 14s

2024-08-20 14:31 UTC, jamilbk approved these changes
LGTM. Looks like CI failure is preventing merge:

https://github.com/firezone/firezone/actions/runs/10466025623/job/28982194439?pr=6309#step:7:43

2024-08-20 14:34 UTC, jamilbk commented
@Patticatti I'll fix the issues and conflicts here to get this merged.

2024-08-20 17:33 UTC, merged