fix(website): Add "read blog" tag above Hero title, adjust hero margins and font sizes
firezone/firezone pull request #6561
Opened 2024-09-02 23:17 UTC by Patticatti

2024-09-03 16:29 UTC, jamilbk requested changes
<img width="264" alt="Screenshot 2024-09-03 at 9 29 08 AM" src="https://github.com/user-attachments/assets/4d517f57-6ed8-4f43-99d3-1fe3bc8ee652">

I think there's a slight black rounded background on the link? Can that be removed?

2024-09-03 16:29 UTC, jamilbk commented on website/public/images/play-icon.png
Can we use a smaller image or just a react-icon here? 12.5KB seems a lot

2024-09-03 16:29 UTC, jamilbk commented on website/src/app/page.tsx
> +          <Link href="/blog">
Could you make this a component so we can easily update the text and link for this?

2024-09-03 19:33 UTC, jamilbk commented on website/src/components/Banner/index.tsx
> -  if (!active) return null;
If you remove this check then the Banner will be unconditionally rendered on all pages.

2024-09-03 22:22 UTC, jamilbk commented on website/src/app/changelog/layout.tsx
> -    <div className="pt-14 flex flex-col">
@Patticatti I think this change needs to be reverted

2024-09-04 00:44 UTC, Patticatti commented
> <img alt="Screenshot 2024-09-03 at 9 29 08 AM" width="264" src="https://private-user-images.githubusercontent.com/167144/364064492-4d517f57-6ed8-4f43-99d3-1fe3bc8ee652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTA4MjEsIm5iZiI6MTcyNTQxMDUyMSwicGF0aCI6Ii8xNjcxNDQvMzY0MDY0NDkyLTRkNTE3ZjU3LTZlZDgtNGY0My05OWQzLTFmZTNiYzhlZTY1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMDQyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTk5Y2QwMThlZTg1NDIxY2ZiMmZhN2NhYzU1MjMwODcyYTRmZDFjOGEzNDIyZjI5YmNlNDk2NDE4OWZmMjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LbsEI5BCnMUUUQoHNQl43A9Mx5CoaMUFNfCCrbPAazc">
> I think there's a slight black rounded background on the link? Can that be removed?

wait wdym rounded background? i think i added it on purpose to give it more contrast

2024-09-04 20:11 UTC, jamilbk requested changes

2024-09-04 20:11 UTC, jamilbk commented on website/src/app/page.tsx
> +          <Banner href="/blog" active={true}>
```suggestion
          <Banner href="/blog" active>
```

2024-09-04 20:13 UTC, jamilbk requested changes

2024-09-04 20:13 UTC, jamilbk commented on website/src/app/page.tsx
> +              <p className="text-sm mr-4">See our latest news</p>
```suggestion
              <p className="text-sm mr-4">New: Internet Resources, REST API, and improved wildcard matching</p>
```

2024-09-04 20:13 UTC, jamilbk commented on website/src/app/page.tsx
> +          <Banner href="/blog" active>
```suggestion
          <Banner href="/blog/sep-2024-update" active>
```

2024-09-04 20:13 UTC, jamilbk commented on website/src/app/page.tsx
> +              <p className="text-sm mr-4">See our latest news</p>
Shouldn't all of this be in the `Banner` component so we don't need to duplicate it in `children`?

2024-09-05 01:07 UTC, Patticatti commented on website/src/app/page.tsx
> +              <p className="text-sm mr-4">See our latest news</p>
Yes lemme fix that

2024-09-05 15:48 UTC, jamilbk approved these changes
Updated the banner style

2024-09-06 01:30 UTC, merged