Add onelogin instructions and reformat authenticate doc
firezone/firezone pull request #699
Opened 2022-06-12 05:14 UTC by gongjason

2022-06-13 16:22 UTC, gongjason commented
@jamilbk flagging so you have a chance to take a look before you create the next release. If no major changes, it'd be good to get this in there :)

2022-06-13 19:31 UTC, jamilbk requested changes
@gongjason Just curious -- why was this guide was added before Keycloak or Authentik? Those are being used by users currently and are self-hosted OIDC providers, so probably a great combo to document / support for us.

2022-06-13 19:31 UTC, jamilbk commented on docs/docs/authenticate/index.md
> +| OIDC provider | offline_access | Link to Guide                                        |
Kinda confused about this table -- is it a feature matrix? Should the `offline_access` header be renamed to like `User Synchronization` or something, and then the fields updated to be like

> 'offline_access' required in `scope` parameter

2022-06-14 00:01 UTC, jamilbk commented
Needs a bit further investigation to see if the `refresh_token` will be provided somehow.

2022-07-21 08:30 UTC, closed without merging