ci: create Sentry release on publish
firezone/firezone pull request #7362
Opened 2024-11-16 09:20 UTC by thomaseizinger

Explicitly creating the Sentry release allows us to associate the commits since the last release with the new one. This might help us to identify potential sources of regressions. For the current releases, I've set them manually to ensure that this automation has something to pick up on for the next release.

2024-11-16 16:28 UTC, jamilbk requested changes
Would it make more sense to move these after the publish artifacts job in the Publish workflow? That way if those fail and we need to delete the release for whatever reason we won't have to go do the same in Sentry.

2024-11-16 16:28 UTC, jamilbk commented on .github/workflows/sentry.yml
> +      - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-11-16 21:00 UTC, thomaseizinger commented
> Would it make more sense to move these after the publish artifacts job in the Publish workflow? That way if those fail and we need to delete the release for whatever reason we won't have to go do the same in Sentry.

Sentry automatically creates a release the first time a certain version logs in. That will already have happened long before we publish because we are testing the version before on staging, CI and locally.

This workflow simply marks it as published and sets the commit range.

2024-11-18 18:18 UTC, jamilbk approved these changes

2024-11-18 18:18 UTC, jamilbk commented on .github/workflows/sentry.yml
> +      - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-11-18 18:18 UTC, jamilbk commented on .github/workflows/sentry.yml
> +      - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-11-18 20:55 UTC, merged