Remove wireguard-tools from firezone.
firezone/firezone pull request #748
Opened 2022-06-22 16:54 UTC by akrousset

Fixes firezone/product#369

## Summary
I've removed `wireguard-tools.rb` which builds `wg` and other utilities in firezone. 
Any reference to `wg` such as environment variables or config attributes were removed
as well. I also removed private key file handling, because we are generating the private
key using `Wireguardex` and I am setting the public key for the interface in the app env
of `fz_vpn`.

I've also refactored `FzVpn.Interface` to remove the `ip` shellouts during interface creation
as we're still handling that via a shell script that runs from `firezone-ctl`. I've also added a new 
function `list_names` to `FzVpn.Interface` so I can check if the interface is missing and create it 
when needed.

2022-06-22 20:09 UTC, jamilbk requested changes
This looks good, but I just thought of one thing -- where is the private key persisted?

2022-06-22 20:09 UTC, jamilbk commented on apps/fz_vpn/lib/fz_vpn/interface.ex
>      private_key = Wireguardex.generate_private_key()
Should this return the `{:ok, private_key}` tuple as well? Alternatively could add exclamation to the function name if you want it to either success or error and crash.

2022-06-22 20:09 UTC, jamilbk commented on apps/fz_vpn/lib/fz_vpn/interface/wg_adapter/live.ex
>    end
```suggestion
defdelegate get_device(name), to: Wireguardex
defdelegate list_devices, to: Wireguardex
defdelegate set_device(config, name), to: Wireguardex
```

2022-06-22 20:09 UTC, jamilbk commented on apps/fz_vpn/lib/fz_vpn/interface/wg_adapter/sandbox.ex
> +        {:ok, public_key} = Wireguardex.get_public_key(config.private_key)
Remove the conditional and crash if no private key?

```suggestion
{:ok, public_key} = Wireguardex.get_public_key(config.private_key)        
```

2022-06-23 15:04 UTC, akrousset commented on apps/fz_vpn/lib/fz_vpn/interface/wg_adapter/sandbox.ex
> +        {:ok, public_key} = Wireguardex.get_public_key(config.private_key)
The private key can be optionally set in Wireguardex, so I was just mirroring that here.

2022-06-23 18:28 UTC, jamilbk submitted a review, later dismissed
LGTM. Also added a couple very minor improvements.

2022-06-23 18:29 UTC, merged