fix(gateway): ensure we run as root
firezone/firezone pull request #7565
Opened 2024-12-20 10:18 UTC by thomaseizinger

The gateway needs to run as `root` in order to access the TUN device as well as configure routes via `netlink`. Not running as `root` leads to "Permission denied" errors being reported to Sentry that are not actionable.

2024-12-20 16:15 UTC, jamilbk reviewed
I'm not sure we want to require the Gateway runs as root. This will likely break the existing systemd installation method, existing Kubernetes users, and likely some other Docker users that don't run the daemon as root.

The Gateway just needs `CAP_NET_ADMIN` to function I believe.

See https://github.com/firezone/firezone/blob/main/scripts/gateway-systemd-install.sh

2024-12-20 16:37 UTC, thomaseizinger commented
> I'm not sure we want to require the Gateway runs as root. This will break the existing systemd installation method, existing Kubernetes users, and likely some other Docker users that don't run the daemon as root.
> 
> The Gateway just needs `CAP_NET_ADMIN` to function I believe.
> 
> See https://github.com/firezone/firezone/blob/main/scripts/gateway-systemd-install.sh

Hmm, I'll see if I can test specifically for that capability.

2024-12-20 17:52 UTC, thomaseizinger commented
https://docs.rs/caps/latest/caps/

This should do the job!

I guess permissions on the file system we can just allow failing on the actual access? Although it would be nice to avoid those Sentry alerts.

2024-12-20 18:12 UTC, jamilbk commented
> https://docs.rs/caps/latest/caps/
> 
> This should do the job!
> 
> I guess permissions on the file system we can just allow failing on the actual access? Although it would be nice to avoid those Sentry alerts.

Probably makes sense to keep Sentry alerts (and `warn!` the user) in some form if `FIREZONE_ID` is not provided and we can't read it from the filesystem I think.

2024-12-24 15:33 UTC, jamilbk requested changes
Hmm, sorry for not catching this earlier. I don't think explicitly checking for the `CAP_NET_ADMIN` capability or running as root is the ideal approach.

In this case, it looks like we would exit incorrectly if the binary is run as root (such as in a Docker container for the default Linux install):

```
root@049e8473c34b:/caps-test# ./target/debug/caps-test

Current permitted caps: Ok({CAP_SETPCAP, CAP_KILL, CAP_FSETID, CAP_AUDIT_WRITE, CAP_SYS_CHROOT, CAP_NET_BIND_SERVICE, CAP_SETUID, CAP_MKNOD, CAP_SETGID, CAP_NET_RAW, CAP_DAC_OVERRIDE, CAP_CHOWN, CAP_FOWNER, CAP_SETFCAP}).

Current effective caps: Ok({CAP_KILL, CAP_DAC_OVERRIDE, CAP_SETUID, CAP_CHOWN, CAP_SYS_CHROOT, CAP_SETFCAP, CAP_NET_BIND_SERVICE, CAP_SETPCAP, CAP_MKNOD, CAP_FSETID, CAP_AUDIT_WRITE, CAP_NET_RAW, CAP_SETGID, CAP_FOWNER}).

Has CAP_NET_ADMIN: Ok(false).
```

Currently, we know the following environments under which the binaries runs would work:

- Running as root
- Running with CAP_NET_ADMIN

However, there are other scenarios that may allow the Gateway to run just fine:

- User added to `netdev` group (Debian)
- udev rules
- File permissions on the /dev/net/tun (or other) device files


Based on the above, would it be feasible to use a more relaxed approach to preemptively check that we can do everything we need to do on startup?

- Check we can add / remove a route
- Check if we can open `/dev/net/tun`
- Check if we can set addresses and open sockets

Another option might be to capture the `NetlinkError: Received a netlink error message Permission denied (os error 13)` error specifically and log it as an `error` to the user but not alert us in Sentry.

Also, bear in mind conditions can change after the Gateway is started, so it's possible we can still hit this error. Probably not a huge deal but something to keep in mind if we see this continue to pop up.

2024-12-24 23:04 UTC, thomaseizinger commented
> Based on the above, would it be feasible to use a more relaxed approach to preemptively check that we can do everything we need to do on startup?
> 
>     * Check we can add / remove a route
> 
>     * Check if we can open `/dev/net/tun`
> 
>     * Check if we can set addresses and open sockets

I thought of this but it doesn't make much sense to do this additionally. Failing to do these already exits the Gateway with an error.

The thinking behind adding a permission check early on was that we can front-load this check which means anything after _is_ actually a bug. Additionally, doing an explicit check first means we can improve the error message.

2024-12-24 23:08 UTC, thomaseizinger commented
An 80% solution could be the following:

- Check if we are root or have `CAP_NET_ADMIN`
- Add a CLI flag to disable preemptive permission checks, allowing people with obscure setups to still make it work

The main thing I want to achieve here is improved UX by exiting early with a good message. At the same time, this allows us to not report these as errors to Sentry.

2024-12-25 10:29 UTC, jamilbk commented
> A "good-enough" solution could be the following:
> 
> * Check if we are root or have `CAP_NET_ADMIN`
> * Add a CLI flag to disable preemptive permission checks, allowing people with obscure setups to still make it work
> 
> The main thing I want to achieve here is improved UX by exiting early with a good message. At the same time, this allows us to not report these as errors to Sentry.

Seems like a good solution!

2024-12-28 04:48 UTC, jamilbk reviewed
LGTM, just a very minor typo.

2024-12-28 04:48 UTC, jamilbk commented on rust/gateway/src/main.rs
> +            "firzone-gateway needs to be executed as `root` or with the `CAP_NET_ADMIN` capability.\nSee https://www.firezone.dev/kb/deploy/gateways#permissions for details."
```suggestion
            "firezone-gateway needs to be executed as `root` or with the `CAP_NET_ADMIN` capability.\nSee https://www.firezone.dev/kb/deploy/gateways#permissions for details."
```

2024-12-29 14:28 UTC, jamilbk approved these changes
So we do have slightly stricter code style enforcement for docs than regular markdown. The thinking there was that these are mdx and often contain tsx blocks and tables.

The line wrap does make diffs slightly harder to work with but since it also seems to apply to the other embedded content and makes it easier to work with doc files side by side in diff views (for example writing a new auth howto which uses many parts of an existing doc) it might be worth keeping.

2024-12-29 14:42 UTC, thomaseizinger commented
> So we do have slightly stricter code style enforcement for docs than regular markdown. The thinking there was that these are mdx and often contain tsx blocks and tables.
> 
> The line wrap does make diffs slightly harder to work with but since it also seems to apply to the other embedded content and makes it easier to work with doc files side by side in diff views (for example writing a new auth howto which uses many parts of an existing doc) it might be worth keeping.

I totally forgot about this and just wrote it this way because I was used to it :)

2024-12-29 22:01 UTC, merged