Update install script docs cloudsmith
firezone/firezone pull request #809
Opened 2022-07-18 19:10 UTC by akrousset

Fixes #786 
Refs firezone/product#200

### Summary
-  [product#200] Add a note to our uninstall script asking for feedback.
- Update install script to automatically setup and install `firezone` package from our Cloudsmith repo.
- Update uninstall script to automatically remove installed Cloudsmith repo.
- Update `docs/deploy/install-server.md` to update install instructions using the Cloudsmith repo.
- Update `docs/administer/upgrade.md` to update upgrade instructions using the Cloudsmith repo.
- Minor fix in preinstall package script to check if the config file exists before grepping.

2022-07-18 21:41 UTC, jamilbk requested changes
Overall LGTM. Some suggestions / questions

2022-07-18 21:41 UTC, jamilbk commented on scripts/install.sh
> +      apt -qqy update
I *think* we want to stick to `apt-get` here so because it's compatible with `DEBIAN_FRONTEND=noninteractive` for users trying to automate this.

2022-07-18 21:41 UTC, jamilbk commented on scripts/install.sh
> +    apt install -y firezone
Same comment here Re: `apt-get`

2022-07-18 21:41 UTC, jamilbk commented on scripts/install.sh
> +  elif [[ "$hostinfo" =~ .*"Amazon Linux 2".*      || \
Might as add Red Hat while we're at it? CentOS should be binary compatible. Also Oracle Linux.

2022-07-18 21:41 UTC, jamilbk commented on scripts/install.sh
> +    | sudo -E bash
Hmm. Did we require `sudo` to be used with this script already? Would this `sudo` be redundant?

2022-07-18 21:41 UTC, jamilbk commented on scripts/uninstall.sh
> +  rm -rf /var/lib/apt/lists/*
Will this break other 3rd party lists the user may have set up?

2022-07-18 21:41 UTC, jamilbk commented on scripts/uninstall.sh
> +echo 'We rely on feedback from users to steer development.' \
Nice

2022-07-18 22:12 UTC, akrousset commented on scripts/install.sh
> +  elif [[ "$hostinfo" =~ .*"Amazon Linux 2".*      || \
Yeah, I kept the same OS names from the previous script version.  I'll add Red Hat and Oracle Linux.

2022-07-18 22:13 UTC, akrousset commented on scripts/uninstall.sh
> +  rm -rf /var/lib/apt/lists/*
The update should restore them but I could be more specific when removing the lists for firezone. This was taken from Cloudsmith, but I thought it was a bit weird as well.

2022-07-18 22:13 UTC, akrousset commented on scripts/install.sh
> +    | sudo -E bash
Ah yeah, that's right!

2022-07-18 22:16 UTC, jamilbk commented on scripts/uninstall.sh
> +  rm -rf /var/lib/apt/lists/*
Ah I see. Hmm. I wouldn't spend too much time then trying to improve this. It's likely they have a good reason for doing it that way.

2022-07-19 14:01 UTC, jamilbk requested changes
lgtm just the merge conflict

2022-07-19 14:49 UTC, jamilbk commented
Lgtm could you prefix branch name with `build/` so the functional test is triggered?

2022-07-19 14:56 UTC, merged

2022-07-19 14:56 UTC, jamilbk commented
Can save that for a new PR