Move auth configs into app
firezone/firezone pull request #812
Opened 2022-07-19 04:31 UTC by princemaple

2022-07-19 04:40 UTC, jamilbk commented
@princemaple Thanks for starting on this. Just FYI, we may not merge this for 0.5.0 just because I think some users are automating this config in their /etc/firezone/firezone.rb config file and if we moved this to the UI without some sort of API for modifying these configs, it may cause an issue.

Open to suggestions though. I was thinking after 0.5.0 is released we can tackle this config issue, v1 REST API, and Prod Docker.

2022-07-19 04:42 UTC, princemaple commented
@jamilbk this will not be a breaking change.

This PR will prioritize user setting but fallback to existing configuration.

2022-07-19 04:43 UTC, princemaple commented on apps/fz_http/lib/fz_http/conf/cache.ex
> +        end
@jamilbk FYI

2022-07-19 04:43 UTC, jamilbk commented
> @jamilbk this will not be a breaking change.
> 
> This PR will prioritize user setting but fallback to existing configuration.

Music to my ears. Well done!

2022-07-19 04:46 UTC, jamilbk commented on apps/fz_http/lib/fz_http/conf/cache.ex
> +        end
👍

2022-07-20 07:03 UTC, princemaple commented
@jamilbk give this branch a go. Haven't fixed the tests yet but the functionalities are working.

2022-07-20 14:48 UTC, jamilbk commented
Looks great. Thanks for adopting the new config layout from @akrousset and nice using those switches.

I have some help text suggestions but this looks really awesome.

2022-07-21 07:27 UTC, princemaple commented
This is ready.

2022-07-21 08:23 UTC, jamilbk requested changes
Initial review. Looking really good. We probably want to show a deprecation notice somewhere to start nudging users to move their config over. I think @akrousset did this in the `omnibus/package-scripts/preinst` shell script, but maybe for now all we need is a short section in the upgrade docs at `docs/docs/administer/upgrade.md`

2022-07-21 08:23 UTC, jamilbk commented on apps/fz_http/lib/fz_http/conf/cache.ex
> +      # XXX: Remove fallbacks before 1.0?
Yeah, this gives a graceful stepping stone. We can detect for these old config file entries (like we're doing with the old SSO config) and print an error if they're still around by next X version.

2022-07-21 08:23 UTC, jamilbk commented on apps/fz_http/lib/fz_http/conf/cache.ex
> +  @no_fallback [:logo]
Cool great

2022-07-21 08:23 UTC, jamilbk commented on apps/fz_http/lib/fz_http/oidc/start_proxy.ex
> +defmodule FzHttp.OIDC.StartProxy do
Nice approach in this module.

2022-07-21 08:23 UTC, jamilbk commented on apps/fz_http/lib/fz_http_web/live/setting_live/security.html.heex
> +        <p>Enable or disable auto creation of new users on OIDC login.</p>
```suggestion
        <p>Enable or disable auto creation of new users when logging in via OIDC for the first time.</p>
```

2022-07-22 03:31 UTC, princemaple commented on apps/fz_http/lib/fz_http/conf/cache.ex
> +      # XXX: Remove fallbacks before 1.0?
Was thinking something like, before 1.0, we release a 0.99 (or, say before 0.8.0, release 0.7.99). In this version, we add a temporary GenServer, that on start, reads the app configs and populates the db. And we document that:

> Before upgrading to 1.0 (or 0.8), please upgrade to 0.99 first (or 0.7.99).

2022-07-24 19:20 UTC, jamilbk approved these changes
lgtm

2022-07-24 19:20 UTC, merged